---
- name: optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Variable configuration.
  ansible.builtin.include_tasks: variables.yml

- name: Setup/install tasks RHEL
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Setup/install tasks Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup/install tasks Arch
  ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  ansible.builtin.set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- name: configure mysql
  ansible.builtin.include_tasks: configure.yml

- name: secure-installation
  ansible.builtin.include_tasks: secure-installation.yml

- name: set up databases
  ansible.builtin.include_tasks: databases.yml

- name: set up users
  ansible.builtin.include_tasks: users.yml

- name: replication
  ansible.builtin.include_tasks: replication.yml
