---
- name: not maintained anymore
  ansible.builtin.fail:
    msg: "Sorry, this role is not maintained anymore :-/"

- name: optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool
